# Generated by Django 4.2.7 on 2023-12-09 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(max_length=1000)),
                ('task_assign_date', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 16, 31, 55, 495952))),
                ('category', models.ManyToManyField(to='category.categorymodel')),
            ],
        ),
    ]
